name: "Build"
on:
  push:
    branches:
      - master
      - flake-updates
  pull_request:
    branches:
      - master
      - flake-updates

jobs:
  x86_64:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
    - name: Build
      run: |
        nix build --print-build-logs
        nix flake check